### ISSUE TITLE
Support for multisession

### ISSUE THREAD

**Issue by zeqk** [VahidN/ASPNETCore2JwtAuthentication#1]
Please can you add support for login using the same user in multiple clients. For example 

When I login in the browser 1, I get a valid access_token and refresh_token
Login in the browser 2, I get a valid access_token and refresh_token, but the browser 1 access_token and refresh_token become invalid

**Comment by VahidN** [comment]
Added via https://github.com/VahidN/ASPNETCore2JwtAuthentication/commit/592ae1648f57d8030bee2517fa0e08e49e33d307. You can configure `AllowMultipleLoginsFromTheSameUser` using the [appsettings.json](https://github.com/VahidN/ASPNETCore2JwtAuthentication/blob/master/src/ASPNETCore2JwtAuthentication.WebApp/appsettings.json#L17) file.

**Comment by zeqk** [comment]
Thank you very much!

**Comment by zeqk** [comment]
@VahidN I learn a lot browsing your project! I forked your project and add a  function https://github.com/zeqk/ASPNETCore2JwtAuthentication/
Revocation by token serial

When the user login, a refresh_code will be generate, including a serial (GUID). Each new access_token and refresh_token generated by this will be include the same serial. When the app generate a new refresh_token, the previous refresh_token will be revoked.

If a refresh_token with the serial is revocated, this make impossible generate a new access_token or refresh_token using it. And each api call, wich use a related access_token, will be not authorized.

This behaivor allows if somebody stole the refresh_token, and use it for get new access_token, the next time the real owner of the refresh_token try to refresh the access_token, it will force the login for the owner and for the attacker

(sorry for my english)
