### ISSUE TITLE
***استفاده از وب سرویس بصورت کد شده***

### ISSUE THREAD

**Issue by javadmjt** [VahidN/ASPNETCore2JwtAuthentication#11]
سلام و احترام
من میخوام از وب سرویس های بدون احراز هویتی که تولید کردم فرد دیگه ای نتونه ازشون تو یه برنامه یا سایت دیگه بدون خبر من استفاده کنه.
میخوام تو انگولار آدرس وب سرویس رو هر بار در زمان فراخوانی به روشی مخفی کنم، 
و با روش های رمزگذاری خاصی و استفاده از کلید مخفی آدرس وب سرویس رو از 
 localhost://api/news/get 
به
 localhost://api/xxxxxx 
تبدیل کردم و سمت سرور با استفاده از همون کلید دوباره رمزگشایی و به کنترلر مربوطه ارسال میشه
مشکلم اینه که زمانی که دارم آدرس رو با یک کلید کد میکنم چون سمت کلاینت هست کلید و کل توابع مربوطه قابل مشاهده هست
همچنین مخفی کردن رو سمت اندروید استفاده کردیم و تا حد امکان تونستیم روش رمز گذاری و رمز گشایی را پنهان کنیم حالا سمت  انگولار با توجه به کلاینت بودن و قابل مشاهده بودن جی اس ها 
پیشنهاد شما برای مخفی سازی،رمز گذاری و رمز گشایی چیه؟
هدف من اینه که کسی نتونه از وب سرویس های من استفاده کنه و مشابه ادرس کد شده مثل 
localhost://api/xxxxxx 
 رو تولید کنه

با تشکر

**Comment by VahidN** [comment]
ربطي به اين پروژه ندارد. لطفا اينجا را اسپم نكنيد
