### ISSUE TITLE
مشکل با [Authorize] و [HttpPost]

### ISSUE THREAD

**Issue by kaktoosii** [VahidN/ASPNETCore2JwtAuthentication#18]
متد هایی که به صورت post هستند و دارای  ValidateAntiForgeryToken هستند همه خطای badrequest  دارد
مثل ChangePasswordController

**Comment by VahidN** [comment]
در اين پروژه دو مثال [Angular](https://github.com/VahidN/ASPNETCore2JwtAuthentication/blob/master/src/ASPNETCore2JwtAuthentication.AngularClient/src/app/core/services/xsrf.interceptor.ts#L20) و [Console](https://github.com/VahidN/ASPNETCore2JwtAuthentication/blob/master/src/ASPNETCore2JwtAuthentication.ConsoleClient/Program.cs#L77) جهت كار با anti-forgery token موجود هستند.

**Comment by kaktoosii** [comment]
ممنون
امکانش هست که dynamic permission رو روی این پروژه هم پیاده کرد؟

**Comment by VahidN** [comment]
[بله.](https://www.dntips.ir/post/3388/%d9%be%db%8c%d8%a7%d8%af%d9%87-%d8%b3%d8%a7%d8%b2%db%8c-%d8%b3%db%8c%d8%a7%d8%b3%d8%aa%e2%80%8c%d9%87%d8%a7%db%8c-%d8%af%d8%b3%d8%aa%d8%b1%d8%b3%db%8c-%d9%be%d9%88%db%8c%d8%a7%db%8c-%d8%b3%d9%85%d8%aa-%d8%b3%d8%b1%d9%88%d8%b1-%d9%88-%da%a9%d9%84%d8%a7%db%8c%d9%86%d8%aa-%d8%af%d8%b1-%d8%a8%d8%b1%d9%86%d8%a7%d9%85%d9%87%e2%80%8c%d9%87%d8%a7%db%8c-blazor-wasm)
