### ISSUE TITLE
درخواست پروژه نمونه wasm standalone

### ISSUE THREAD

**Issue by saeed-m** [VahidN/ASPNETCore2JwtAuthentication#33]
# Summary of the issue
در دسترسی به ای پی آی های محافضت شده در postman و blazor wasm مشکلی هست، لطف میکنید یک پروژه نمونه blazor wasm standalone هم به مثال ها اظافه کنید.

**Comment by VahidN** [comment]
يك نمونه [اينجا](https://github.com/VahidN/BlazorWasmDynamicPermissions) هست. [اطلاعات بيشتر](https://www.dntips.ir/post/3388/%d9%be%db%8c%d8%a7%d8%af%d9%87-%d8%b3%d8%a7%d8%b2%db%8c-%d8%b3%db%8c%d8%a7%d8%b3%d8%aa%e2%80%8c%d9%87%d8%a7%db%8c-%d8%af%d8%b3%d8%aa%d8%b1%d8%b3%db%8c-%d9%be%d9%88%db%8c%d8%a7%db%8c-%d8%b3%d9%85%d8%aa-%d8%b3%d8%b1%d9%88%d8%b1-%d9%88-%da%a9%d9%84%d8%a7%db%8c%d9%86%d8%aa-%d8%af%d8%b1-%d8%a8%d8%b1%d9%86%d8%a7%d9%85%d9%87%e2%80%8c%d9%87%d8%a7%db%8c-blazor-wasm).
