### ISSUE TITLE
نحوه ارسال درخواست از کلاینت های ویندوزی یا اندرویدی

### ISSUE THREAD

**Issue by miladsoft** [VahidN/ASPNETCore2JwtAuthentication#5]
من برای ارسال درخواست از کلاینت ویندوزی به سرور         
services.AddAntiforgery(x => x.HeaderName = "X-XSRF-TOKEN"); 
و
app.UseAngularAntiforgeryToken(); 
و
{
          options.Filters.Add(new AutoValidateAntiforgeryTokenAttribute());
});

را غیر فعال کردم و کد زیر درست کار کرد ولی اگر بخواییم به شکلی که برنامه انگولار موجود در خود سورس درخواست ارسال میکنه این کار رو انجام بدیم به چه صورته ؟ 

ممنون میشم راهنمایی کنید . 

    var httpWebRequest = (HttpWebRequest)WebRequest.Create("http://localhost:5000/api/account/login");
            httpWebRequest.ContentType = "application/json";
            httpWebRequest.Method = "POST";

            using (var streamWriter = new StreamWriter(httpWebRequest.GetRequestStream()))
            {

                Dictionary<string, string> dic = new Dictionary<string, string>() {
                    {"username","Vahid"},
                    {"password","1234"}};
                var json = JsonConvert.SerializeObject(dic);
                streamWriter.Write(json);
                streamWriter.Flush();
                streamWriter.Close();
            }

            var httpResponse = (HttpWebResponse)httpWebRequest.GetResponse();
            using (var streamReader = new StreamReader(httpResponse.GetResponseStream()))
            {
                var result = streamReader.ReadToEnd();
            }

**Comment by VahidN** [comment]
follow [this sample](https://github.com/VahidN/JwtWithWebAPI/blob/master/JwtWithWebAPI.ConsoleClient/Program.cs).

**Comment by VahidN** [comment]
I added a [ConsoleClient sample](https://github.com/VahidN/ASPNETCore2JwtAuthentication/tree/master/src/ASPNETCore2JwtAuthentication.ConsoleClient) to show how to send anti-forgery and access tokens to the server.
