### ISSUE TITLE
Login access denied if I open new tab

### ISSUE THREAD

**Issue by jaskevs** [VahidN/ASPNETCore2JwtAuthentication#6]
# Summary of the issue
After login if try to open another page in next tab it is asking me to login again. Is this an expected behavior?

## Example code/Steps to reproduce:
- Use google chrome
- Login to application
- Right click on "Call Protected Api" link on top and Open in New Tab
- It will endup in access denied page

**Comment by jaskevs** [comment]
I checked closed issues and found you were not using local storage by default. and I checked Remember me checkbox at login and it works perfectly. 

Can I ask you along with this question, is this way of refreshing tokens is the right way to go for bigger applications as well?

**Comment by VahidN** [comment]
- Yes, session storage won't be shared across different tabs (if you don't select remember me which uses local storage and it will be shared across all open tabs).
- It's a timer and it will be triggered before the current access token is about to be expired. So if the token provides the correct info, it will work.

**Comment by VahidN** [comment]
Refresh token timer will be stared once at the startup of the app and won't be started again if you open another tabs. So changing the pages won't affect its lifetime, it's still running behind the scene. It uses a singleton service and its life time is equal to the life time of the entire app.
